#!/bin/bash

# clean data
find data -type f \( -iname \*.root -o -iname \*.log \)|while read f
do
	rm "$f"
done

# re-compile programs
make clean || exit 1
make -j8 || exit 2

# re-run everything
datasets="data/fill*/Totem1"

./run -wait "distill.cc" $datasets -d "45b_56b 45b_56t 45t_56b 45t_56t" || exit 1

./run -wait "distributions.cc" $datasets -O "-bootstrap 1 -details 5" || exit 10
./run -wait "distributions_anti.cc" $datasets -danti || exit 11

# TODO: uncomment once the RP directory is restored
#./run -wait "process_timber.cc" $datasets || exit 20

./run -wait "alignment.cc" $datasets || exit 21
./run -wait "eff3outof4.cc" $datasets || exit 22
./run -wait "eff3outof4_details.cc" $datasets || exit 22
./run -wait "pileup.cc" $datasets || exit 23
#./run -wait "unfolding_cf_mc.cc" $datasets || exit 24
./run -wait "unfolding_cf_ni.cc" $datasets || exit 25

./run -wait "resolution_fit.cc" "alignment_fit.cc" "eff3outof4_fit.cc" $datasets || exit 30

./run -wait "distributions.cc" $datasets || exit 40

./run -wait "alignment_final.cc" $datasets || exit 50

cd data
./merge &> "merge.log" || exit 60
