#!/bin/sh

# define directories
job_dir="/afs/cern.ch/work/j/jkaspar/work/analyses/elastic/450GeV/beta100/4rp/test/acceptance_code"

# run the process
cd "$job_dir"

{ time ./validation_with_mc $options -output "$output" ; } &> "$log"
