#!/bin/bash

cwd=`pwd`

cd "/afs/cern.ch/work/j/jkaspar/work/software/ctpps/production/CMSSW_10_6_17"
source environment

compName=$(uname -n)
export compName="${compName%%.*}"

function CalculatePrompt()
{
	cwd=`pwd`
	cwd=${cwd/\/afs\/cern.ch\/work\/j\/jkaspar/...}
	cwd=${cwd/\/analyses\/ctpps/}
}

PROMPT_COMMAND="CalculatePrompt"
export PS1="\[\033[00;34m\]${compName} \[\033[00;33m\]${CMSSW_VERSION}\[\033[00;32m\] \$cwd> \[\033[00m\]"

export GSL_DIR="/cvmfs/cms.cern.ch/slc7_amd64_gcc820/external/gsl/2.2.1-pafccj2"

cd "$cwd"

echo "CMSSW_BASE=$CMSSW_BASE"
