#!/bin/bash

cwd=`pwd -P`

ref_dir="../../beta100/4rp"

for f_ref in $ref_dir/{*.cc,make_synchronisation_links,run} $ref_dir/classes/*.{cc,hh} $ref_dir/test/{compare.cc,run_test} $ref_dir/studies/systematics/*.{cc,hh}
#for f_ref in $ref_dir/4rp/plots/*/*.asy
do
	f_loc=${f_ref##*4rp/}

	f_lnk=${f_loc/./.HighBeta.}
	if [ "$f_lnk" == "$f_loc" ]; then f_lnk="$f_loc.HighBeta"; fi

	cmp --silent "$f_ref" "$f_loc"
	identical="$?"

	echo "* $f_loc ($identical)"

	if [ "$identical" == "0" ]
	then
		echo "    files identical, link not made"
	else
		echo "    making link"
		rm -f "$f_lnk"
		ln -sr "$cwd/$f_ref" "$cwd/$f_lnk"
	fi
done
