#!/bin/bash

#----------------------------------------------------------------------------------------------------

function PrintUsage()
{
	echo -e "USAGE: $0 <option> <src file> <option> <dir> <dir> ..."
	echo -e "OPTIONS"

	echo -e "	-h, --help		print this help and exit"
	echo -e "	-d <string>		select diagonals"
	echo -e "	-dcomb			select 'combined' diagonal"
	echo -e "	-danti			select anti-diagonals"
	echo -e "	-O <option>		pass the option to the program"
	echo -e "	-wait			wait for all programs to finish"
#	echo -e "	-batch			prepare job for LXBATCH instead of executing locally"
#	echo -e "	-submit			submit job to LXBATCH, implies -lxbatch option"
}

#----------------------------------------------------------------------------------------------------

function RunOneDiagonal()
{
	local optionsStr=""
	if [ ! "$run_options" == "" ]
	then
		optionsStr=" ($run_options)"
	fi

	label="$tag @ $dir:$diag"
	log="${tag}_${diag}.log"

	echo "$label > running$optionsStr"
	{ time "$binDir/$bin" $run_options -dgn "$diag" ; } &> "$log"
	errCode="$?"
	case "$errCode" in
		0)
			echo "$label > done"
			return 0
			;;

		$rcIncompatibleDiagonal)
			rm "$log"
			return 0
			;;

		*)
			echo "$label > run error ($errCode)"
			tail -n 5 "$log"
			return 1
			;;
	esac
}

#----------------------------------------------------------------------------------------------------

function RunOneDirectory()
{
	cd "$dir"

	for prog in ${programs[*]}
	do
		tag="${prog%.*}"
		bin=".$tag"

		for diag in ${diagonals[*]}
		do
			RunOneDiagonal &
			pids="$pids $!"
		done
	done

	cd - &>/dev/null
}

#----------------------------------------------------------------------------------------------------

directories=()
programs=()
diagonals=("45b_56t" "45t_56b" "combined")

compile="y"

run_options=""

waitForPrograms="n"
pids=""

batch="n"
submit="n"

rcIncompatibleDiagonal=123

#----------------------------------------------------------------------------------------------------

if [ $# -le 0 ]
then
	PrintUsage
	exit 1
fi

while [ -n "$1" ]
do
	case "$1" in
		"-h" | "--help")
			PrintUsage
			exit 1
			;;

		"-d")
			shift
			diagonals=($1)
			;;

		"-dcomb")
			diagonals=("combined")
			;;

		"-danti")
			diagonals=("45b_56b" "45t_56t")
			;;

		"-O")
			shift
			run_options="$1"
			;;

		"-doNotCompile")
			compile="n"
			;;

		"-wait")
			waitForPrograms="y"
			;;

		"-lxbatch")
			lxbatch="y"
			;;

		"-submit")
			lxbatch="y"
			submit="y"
			;;

		*)
			if [ -f "$1" ]
			then
				programs+=("$1")
			else
				if [ -f "$1/config.py" ]
				then
					directories+=("$1")
				else
					echo "ERROR: $1 is not understood."
					PrintUsage
					exit 2
				fi
			fi
			;;
	esac

	shift
done

# compile all programs
if [ "$compile" == "y" ]
then
	for prog in ${programs}
	do
		target=".${prog%.*}"
		make "$target" || exit 3
	done
fi

binDir=`pwd -P`

# execute for directories
for dir in ${directories[*]}
do
	RunOneDirectory
done

# wait for programs, if desired
if [ "$waitForPrograms" == "y" ]
then
	error="n"

	for p in $pids
	do
		wait $p || error="y"
	done

	if [ "$error" == "y" ]
	then
		exit 1
	fi
fi
