#!/bin/bash

topDir="./"

n_threads="4"

#----------------------------------------------------------------------------------------------------

function ProcessOneThread()
{
	local buffer="$1"

	for file in $buffer
	do
		p=${file%/*}
		f=${file##*/}

		cd "$p"

		asy "$f" &> /dev/null
		res="$?"

		cd - > /dev/null

		if [ $res -eq 0 ]
		then
			echo "$f: done"
		else
			echo "$f: ERROR"
		fi
	done
}

#----------------------------------------------------------------------------------------------------

# remove all existing PDFs
find "$topDir" -name *.pdf|while read f; do rm "$f"; done

# collect input files
idx=0
input=()
for file in `find "$topDir" -mindepth 2 -name "*.asy"`
do
	input[$idx]="${input[$idx]} $file"
	idx=$(( (idx+1) % n_threads ))
done

# run in parallel
for (( idx=0; idx<n_threads; idx++))
do
	ProcessOneThread "${input[$idx]}" &
done

wait

echo "-----------------------"
echo "ALL done"
