#!/bin/bash

for d in ../data/fill*
do
    fill=${d#*fill}

    echo ""
    echo "// fill $fill"

    cat $d/Totem1/distributions_45b_56t.log | grep "run boundary" | while read line
    do
        run=`echo $line|awk '{print $4}'`
        from=`echo $line|awk '{print $6}'`
        to=`echo $line|awk '{print $8}'`

        run=${run%,}

        echo "AddRun(\"$fill\", $run, $from, $to);"
    done

    cat $d/Totem1/distributions_45b_56t.log | grep "excl boundary" | while read line
    do
        from=`echo $line|awk '{print $4}'`
        to=`echo $line|awk '{print $6}'`

        run=${run%,}

        echo "AddExcl(\"$fill\", $from, $to);"
    done
done

