#!/bin/sh

export HOME="/afs/cern.ch/exp/totem/scratch/jkaspar"

source "/cvmfs/cms.cern.ch/cmsset_default.sh"
cd "$CMSSW_BASE/src"
eval `scram runtime -sh`

# define directories
job_dir="$JOB_DIR"

# run the process
cd "$job_dir"

$COMMAND