#!/bin/bash

#----------------------------------------------------------------------------------------------------
# defaults

diagonals=(
	"45b_56t"
	"45t_56b"
)

configurations=(
# TODO: uncomment others when ready
	"fit_1/none"

	"fit_1/sh-thx"
	"fit_1/sh-thx-LRasym"

	"fit_1/sh-thy"
	"fit_1/sh-thy-LRasym"
	"fit_1/sh-thy-TBuncor"
	"fit_1/sh-thy-TBuncor-LRasym"

	"fit_1/tilt-thx-thy"
	"fit_1/tilt-thx-thy-LRasym"

#	"fit_1/sc-thxy-mode1"
#	"fit_1/sc-thxy-mode2"
#	"fit_1/sc-thxy-mode3"
#
#	"fit_1/dx-sigma"
#	"fit_1/dy-sigma"
#	"fit_1/dx-non-gauss"
#	"fit_1/dx-mx-corr"
#	"fit_1/dy-my-corr"
#
#	"fit_1/eff-intercept"
#	"fit_1/eff-slope"
#
	"fit_1/beam-mom"
#
#	"fit_1/mx-sigma"
#	"fit_1/my-sigma"
#
#	"fit_1/norm"
#
#	"fitN-4/none"
)

stat=""

# TODO: migrate to HTCondor
use_lxbatch="n"
bsub_options="pool>1"
bsub_queue="1nd"
submit="n"

wait_for_jobs="n"

#----------------------------------------------------------------------------------------------------
# parse command line

function PrintUsage()
{
	echo "USAGE: run_multiple_mc_simu [option] [option] ..."
	echo "OPTIONS:"
	echo "    -events <int>    number of events to simulate"
	echo "    -lxbatch         prepare jobs on LXBATCH instead of local machine"
	echo "    -submit          submit jobs to LXBATCH"
	echo "    -queue <string>  set LXBATCH queue"
	echo "    -wait            wait for jobs run in background"
}

while [ "$1" != "" ]
do
	key="$1"

	case $key in
		-h|--help)
			PrintUsage
			exit 0
		;;

		-events)
			stat="$2"
			shift
		;;

		-lxbatch)
			use_lxbatch="y"
		;;

		-submit)
			submit="y"
		;;

		-queue)
			bsub_queue="$2"
			shift
		;;

		-wait)
			wait_for_jobs="y"
			shift
		;;

		*)
			echo "ERROR: unknown option '$key'."
			PrintUsage
			exit 1
		;;
	esac

	shift
done


#----------------------------------------------------------------------------------------------------
# consistency check

if [ "$stat" == "" ]
then
	echo "ERROR: statistics not defined. Use '-events' option."
	PrintUsage
	exit 2
fi

#----------------------------------------------------------------------------------------------------

function ExecuteOne()
{
	echo "* $dir/$scenario"

	local cwd=`pwd -P`

	local tag="$scenario"

	local job_dir="$cwd"
	local job_file="$dir/.${tag}.job"
	local job_log_file="$dir/.${tag}.log_job"

	local command="{ time ./mc_simu -model \"$model\" -dgn \"$diagonal\" -scenario \"$scenario\" -events \"$stat\" -output \"$dir/$scenario.root\" ; } \&> \"$dir/$scenario.log\""

	cat "job_template" | sed "\
			s|\$CMSSW_BASE|$CMSSW_BASE|; \
			s|\$JOB_DIR|$job_dir|; \
			s|\$JOB_LOG_FILE|$job_log_file|; \
			s|\$COMMAND|$command|; \
		" > "$job_file"
	chmod u+x "$job_file"

	if [ "$use_lxbatch" == "y" ]
	then
		if [ "$submit" == "y" ]
		then
			result=`bsub -R "$bsub_options" -q "$bsub_queue" -o /dev/null -e /dev/null "$cwd/$job_file"`
			echo "    $result"
		else
			echo "    would be submitted to $bsub_queue"
		fi
	else
		"./$job_file" &
	fi
}

#----------------------------------------------------------------------------------------------------

make -C ../../ -j8 || exit 1

for diagonal in ${diagonals[*]}
do
	for configuration in ${configurations[*]}
	do
		model=${configuration%%/*}
		scenario=${configuration##*/}

		dir="data-mc/$stat/$diagonal/$model"
		mkdir -p "$dir"

		ExecuteOne
	done
done

#----------------------------------------------------------------------------------------------------

if [ "$wait_for_jobs" == "y" ]
then
	wait
fi
